version: '3.2'

services:
  rivet:
    build: 
      context: ./rivet
      cache_from:
        - gcr.io/media-9x16/rivet
    ports:
      - 8554:8554
      - 8883:8883
    volumes:
      - ./rivet/src/:/opt/src/
      - ./rivet/debug/:/opt/debug/
      - ./rivet/Cargo.toml:/opt/Cargo.toml
    command: sleep 100000
    environment:
      - GST_DEBUG_DUMP_DOT_DIR=/opt/debug/
    image: gcr.io/media-9x16/rivet
  browser-debug:
    build: ./browser-debug
    ports:
      - 8081:80
    volumes: 
      - ./browser-debug:/usr/share/nginx/html
